name: JueJin_Helper87467
on:
  push:
  schedule:
    - cron: "0 23 * * *" # `分 时 天 月 周` 时按照标准时间 北京时间=标准时间+8 每天早上七点自动执行

  workflow_dispatch:

jobs:
  check_in:
    runs-on: ubuntu-latest
    steps:
      # 切换分支
      - name: Checkout
        uses: actions/checkout@master

      # 使用 node:14
      - name: 使用 Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      # npm install
      - name: npm install
        run: |
          npm install
        env:
          CI: true

      # 运行脚本
      - name: 运行脚本
        run: |
          COOKIE='${{ secrets.COOKIE87467 }}' TOKEN='${{ secrets.TOKEN87467 }}' USER='${{ secrets.USER }}' PASS='${{ secrets.PASS }}' TO='${{ secrets.TO }}' TEL='87467' npm start
        env:
          CI: true
