name: JueJin_Helper30791
on:
  push:
  schedule:
    - cron: '0 17 * * *' # `分 时 天 月 周` 时按照标准时间 北京时间=标准时间+8 每天早上七点自动执行
jobs:
  check_in:
    runs-on: ubuntu-latest
    steps:
      # 切换分支
      - name: Checkout
        uses: actions/checkout@master

      # 下载 git submodule
      - uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update --init --recursive

      # 使用 node:14
      - name: 使用 Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      # npm install
      - name: npm install
        run: |
          npm install
        env:
          CI: true

      # 运行脚本
      - name: 运行脚本
        run: |
          COOKIE='${{ secrets.COOKIE30791 }}' TOKEN='${{ secrets.TOKEN30791 }}' USER='${{ secrets.USER }}' PASS='${{ secrets.PASS }}' TO='${{ secrets.TO }}' TEL='30791' npm start
        env:
          CI: true
